export const GET_CURRENT_POSTITION = 'GET_CURRENT_POSTITION';
export const FETCH_MARKERS_DETAILS = 'FETCH_MARKERS_DETAILS';
export const FETCH_SEARCH_FILTERS_DATA = 'FETCH_SEARCH_FILTERS_DATA';
export const RESET = 'RESET';
